title: Goshi Aoki
description: M.S. in Computer Science and Technology, Zhejiang University

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
show_downloads: false
is_project_page: true

# button_linkedin:
#   url: https://www.linkedin.com/in/goshiaoki/
#   text: LinkedIn

button_x:
  url: https://x.com/goshi_aoki
  text: X

button_github:
  url: https://github.com/goshiaoki
  text: GitHub

button_linkedin:
  url: https://www.linkedin.com/in/goshiaoki/
  text: LinkedIn

button_facebook:
  url: https://www.facebook.com/goshi.aoki/
  text: Facebook

button_cv:
  url: https://drive.google.com/file/d/1h-osZdykv4dK4ItyGJq2v1R_78MKGs91/view?usp=sharing
  text: CV

